[package]
name = "matura-arbeit"
version = "0.1.0"
edition = "2021"

resolver = "2"

[dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.24.0"
bevy-tnua = "0.18.0"
bevy-tnua-rapier2d = "0.6.0"
bevy_rapier2d = "0.26.0"
catppuccin-egui = { version = "5.1.1", features = [ "egui27" ], default-features = false }
easer = "0.3.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
