[package]
name = "matura-arbeit"
version = "0.1.0"
edition = "2021"

resolver = "2"

[dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.24.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
